### ISSUE TITLE
displaying on main thread, success and failure

### ISSUE THREAD

**Issue by karlhungus** [pseudomuto/Retired#4]
In the instructions you might want to tell people to dispatch display on the main thread:

```swift
       dispatch_async(dispatch_get_main_queue()) {
          message.presentInController(rootViewController)
        }
```

I don't have conclusive proof that this is a problem (haven't seen an error, but am told by someone who knows ios better than me 😄  @hweetty)

We also ran into a problem where we only want to load more of the app further if retired says 👍 , but don't want to if it fails. This means that we dispatch requests to the server for data before retired has finished so we can display our main screen, and we run into 🐔 and 🍳  problems where we'd like to force update but retired happens after that initial load (https://github.com/Shopify/frenzy-ios/pull/351).

So ideally we'd see something like this

1 . Load app
2. retired check
  1. none -> continue
  2. forced -> do alert display and 💩 the 🛏 
  3. recommended -> display alert and whatnot

Pros:
 - you can pretty be sure that people will be forced to update without doing your code
Cons:
 - slower

I'll try to pr these if you think they make sense.

**Comment by karlhungus** [comment]
@pseudomuto  opinions?

**Comment by pseudomuto** [comment]
You mean something like this (obviously not with `DISPATCH_TIME_FOREVER`)?

```swift
let semaphore = dispatch_semaphore_create(0)

try! Retired.check() { updateRequired, message, error in
    // do your thing here...
    dispatch_semaphore_signal(semaphore)
}

dispatch_semaphore_wait(semaphore, DISPATCH_TIME_FOREVER)
```

**Comment by karlhungus** [comment]
quietly going to slink away from this one 😛
